package com.quinsoft.zeidon.javascript

import com.quinsoft.zeidon.objectdefinition.LodDef
import com.quinsoft.zeidon.standardoe.JavaObjectEngine
import com.quinsoft.zeidon.scala.Implicits._
import scala.collection.JavaConversions._
import java.io.File
import java.nio.file.Files
import java.nio.file.Paths
import com.quinsoft.zeidon.Task
import com.quinsoft.zeidon.scala.View

class GenerateXdmForTypescript( val applicationName: String, val destinationDir: String ) {

    val oe = JavaObjectEngine.getInstance
    val application = oe.getSystemTask.getApplication( applicationName )
    var lodDef: LodDef = null

    def generate() {
        oe.forTask( applicationName ) ( task => {
            task.log.info("Starting Typescript generation" )
            new File( destinationDir ).mkdir()
            val xdmfile = application.getObjectDir() + "/zeidon.xdm"
            generateXdm( task, xdmfile )
            println( "Done" )
        })
    }

    private def generateXdm( task: Task, filename: String ) = {
        val xdm = task.deserializeOi().setApplication( "ZeidonSystem" ).setLodDef( "tzdmxgpo" ).fromFile( filename ).unpickle
        printToFile( s"$destinationDir/${application.getName}-DomainList.ts" )( writer => {
            writer.println( s"""
// Generated from ${filename}
import { Domain } from '@zeidon/core';

export const ${application.getName()}_DomainList = {
""" );

            xdm.Domain.each{ writeDomain( writer, xdm ) }
            writer.println( s"""}""" )
        } )

        val functionFile = s"$destinationDir/${application.getName}-DomainFunctions.ts"
        if ( ! Files.isRegularFile( Paths.get( functionFile ) ) ) {
            printToFile( functionFile )( writer => {
                writeDefaultFunctionsFile( writer, application.getName )
            })
        }
    }

    private def writeDomain( writer: java.io.PrintWriter, xdm : View ) {
        writer.println( s"""    "${xdm.Domain.Name}" : {
        name:  "${xdm.Domain.Name}",
        class: "${xdm.Domain.JavaClass}", """ )

        if ( xdm.Domain.DomainType == "Table" ) {
            var defaultContext = ""

            writer.println( s"""        domainType:  "T",
        contexts: {""" )

            xdm.Context.each{
                writeTableContexts( writer, xdm )
                if ( xdm.Context.IsDefault == "Y" )
                    defaultContext = xdm.Context.Name
            }

            writer.println( s"""        },
        defaultContext: "$defaultContext" """ )
        }

        writer.println( s"""    } as Domain,
""" )
    }

    private def writeTableContexts( writer: java.io.PrintWriter, xdm : View ) {
        writer.println( s"""            "${xdm.Context.Name}": {
                name: "${xdm.Context.Name}",
                entries: {""" )

        xdm.TableEntry.each {
            writer.println( s"""                    "${xdm.TableEntry.InternalValue}": "${xdm.TableEntry.ExternalValue}",""" )
        }

        writer.println( s"""                }
            },""" )
    }

    private def printToFile(filename: String)(op: java.io.PrintWriter => Unit) {
        val p = new java.io.PrintWriter(new File(filename))
        try { op(p) } finally { p.close() }
    }

    private def writeDefaultFunctionsFile( writer: java.io.PrintWriter, appName: String ) {
        writer.println( s"""// Default domain functions generated by Zeidon
import { DefaultDomainFunctions } from "@zeidon/domains"
import { DomainFunctions } from "@zeidon/core"

export const ${appName}_DomainFunctions =
    {
        ...DefaultDomainFunctions,
        // App-specific domain functions can go here.
        ...{}
    };
""" )
    }
}
