name: Zeidon CI

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'adopt'
        settings-path: ${{ github.workspace }} # location for the settings.xml file
    - uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Build with Maven
      if: github.ref == 'refs/heads/current-dev'
      run: mvn install

    - uses: actions/checkout@v3
    - name: Set up Maven Central Repository
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'adopt'
        server-id: ossrh
        server-username: MAVEN_USERNAME
        server-password: MAVEN_PASSWORD
        gpg-private-key: ${{ secrets.gpg_private_key }} # Value of the GPG private key to import
        gpg-passphrase: GPG_PASSPHRASE # env variable for GPG private key passphrase

    - name: Publish package
      run: mvn --batch-mode deploy -DskipTests=true -P 'deploy,!test-projects'
      env:
        MAVEN_USERNAME: ${{ secrets.nexus_username }}
        MAVEN_PASSWORD: ${{ secrets.nexus_password }}
        GPG_PASSPHRASE: ${{ secrets.gpg_passphrase }}
