name: Zeidon CI

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'adopt'
        settings-path: ${{ github.workspace }} # location for the settings.xml file
    - uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Build with Maven
      if: github.ref == 'refs/heads/current-dev'
      run: mvn install

    - name: Deploy snapshot
      if: github.ref == 'refs/heads/current-dev'
      run: mvn -P !test-projects -DskipTests=true --batch-mode deploy
      env:
        MAVEN_USERNAME: ${{ secrets.NEXUS_USERNAME }}
        MAVEN_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
