name: Zeidon CI

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'adopt'
        settings-path: ${{ github.workspace }} # location for the settings.xml file
    - uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Build with Maven
      if: github.ref == 'refs/heads/current-dev'
      run: mvn install

    - name: Release Maven package
      if: github.ref == 'refs/heads/current-dev'
      uses: samuelmeuli/action-maven-publish@v1
      with:
        gpg_private_key: ${{ secrets.gpg_private_key }}
        gpg_passphrase: ${{ secrets.gpg_passphrase }}
        nexus_username: ${{ secrets.nexus_username }}
        nexus_password: ${{ secrets.nexus_password }}
        maven_profiles: deploy,!test-projects
